# -*- coding: utf-8 -*-
"""sistema-basico-elevador

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQKVaOgIcZlDl_jV90URk3EqXrojdhf5
"""

import random as rd
import numpy as np

andar_sorteado = []
quant_sorteado = []

for i in range(0, 3):
  #Sistema de sorteio do andar do elevador
  andar_elevador = rd.randint(0, 5)
  andar_sorteado.append(andar_elevador)

  #Sistema de sorteio da quantidade de pessoas no elevador
  quant_elevador = rd.randint(0, 5)
  quant_sorteado.append(quant_elevador)

#Comunicação com o usuário para obter sua localização no prédio
while True:
  passageiro = str(input("Digite seu andar:\t")).lstrip('0').strip('-')
  
  if passageiro > '5' or passageiro.isnumeric() == False:
    print("Dígito inválido.")
  else:
    print("Seja bem-vindo.")
    break

elevador_prox = []
#Sistema de cálculo do elevador mais próximo
for j in range(len(andar_sorteado)):
  passageiro_num_inteiro = int(passageiro)
  calculo_prox = passageiro_num_inteiro - andar_sorteado[j]
  elevador_prox.append(abs(calculo_prox))

#Amostragem dos resultados para o usuário
print('')
print(f'Posição do elevador 01: {andar_sorteado[0]} | Quantidade de pessoas: {quant_sorteado[0]} \nPosição do elevador 02: {andar_sorteado[1]} | Quantidade de pessoas: {quant_sorteado[1]}\nPosição do elevador 03: {andar_sorteado[2]} | Quantidade de pessoas: {quant_sorteado[2]}\n')

elev_mais_prox = elevador_prox.index(min(elevador_prox))+1
elev_mais_vago = quant_sorteado.index(min(quant_sorteado))+1

if elev_mais_prox  == elev_mais_vago and quant_sorteado[elev_mais_prox ] < 5:
  print(f'O melhor elevador é o:\t{(elev_mais_prox  + elev_mais_vago)/2}')
else:
  quant_minima = np.argmin(quant_sorteado)
  print(f'o melhor elevador é  o:\t {quant_minima+1}')