# -*- coding: utf-8 -*-
"""teste.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQKVaOgIcZlDl_jV90URk3EqXrojdhf5
"""

import random as rd

andar_sorteado = []

for andar_elevador in range(0, 5):
  andar_elevador = rd.randint(0, 5)
  andar_sorteado.append(andar_elevador)
print(andar_sorteado)

peso_sorteado = []

for peso_elevador in range(0, 5):
  peso_elevador = rd.randint(99, 301)
  peso_sorteado.append(peso_elevador)
print(peso_sorteado)

while True:
  passageiro = input("Digite seu andar:\t").lstrip('0').strip('-')
  
  if passageiro > '5' or passageiro.isnumeric() == False:
    print("Dígito inválido.")
  else:
    print("Seja bem-vindo.")
    break

elevador_prox = []

for i in range(len(andar_sorteado)):
  passageiro_num_inteiro = int(passageiro)
  calculo_prox = passageiro_num_inteiro - andar_sorteado[i]
  elevador_prox.append(calculo_prox)

print('')
print(elevador_prox)
print(andar_sorteado)

print(f'menor valor: {min(elevador_prox)}')
print(f'index do menor valor: {elevador_prox[min(elevador_prox)]}')